### PR TITLE
Refresh the layout, simplify start page, add screenshot

### PR DESCRIPTION
**Pull request by thp**
Proposed webpage refresh. Comments welcome :)

Left: Current start page, right: proposed new start page.

Screenshot from 2022-03-24 19-59-41

### CODE REVIEW

**Comment by auouymous** [comment]
I like everything about it.

Why is ubuntu ppa with others and not linux? Should it mention gtk+, or better gtk3, in the first line with python?

**Comment by thp** [comment]
> Why is ubuntu ppa with others and not linux?

I figured that since Ubuntu basically wants everybody to use Snaps, the Ubuntu PPA is probably only for "experts" (who want to avoid Snap and Flatpak), and the beginners should use the Flatpak, so this is placed more prominently.

In general, Sailfish OS is also Linux, but both Sailfish OS and Ubuntu PPA may be "special enough" to be put into the own line for experts to still find. Linux Desktop users should probably be directed towards Flatpak (for the latest version) or distro packages (for easy "native" packaging) at this point in time.

> Should it mention gtk+, or better gtk3, in the first line with python?

As part of the simplification (and to visually fit it into one line) I removed the "using GTK+", since the toolkit should either not make much difference, or the "g" in "gPodder" should clue people in. Of course, the same could be said about "Python", since the language it's written in should not make much difference.

This might actually be even nicer:

"gPodder is a simple, open source podcast client."

The language (Python) and UI toolkit (GTK3) can be found out easily by clicking through the "Source code" link, as the README.md mentions it. Maybe the screenshot also suggests it's GTK with client-side decorations, not sure.

**Comment by auouymous** [comment]
Okay, I know nothing about ubuntu and just wanted to make sure it wasn't a mistake.

> "gPodder is a simple, open source podcast client."

I'm fine with that. And technically gpodder supports gtk and qt, so best not to mention it.

> Maybe the screenshot also suggests it's GTK with client-side decorations

It actually says nothing about the project for the blind. I assume ` Screenshot of gPodder` expands to the screenshot, does the `Screenshot of gPodder` become its alt tag?

The gpodder logo has a blank alt tag and should be `alt="gPodder logo"`.

**Comment by thp** [comment]
> > "gPodder is a simple, open source podcast client."
> 
> I'm fine with that. And technically gpodder supports gtk and qt, so best not to mention it.

Done.

> > Maybe the screenshot also suggests it's GTK with client-side decorations
> 
> It actually says nothing about the project for the blind. I assume ` Screenshot of gPodder` expands to the screenshot, does the `Screenshot of gPodder` become its alt tag?

Yes, I made the text more clear, and it should be the `alt=` text according to this:

https://www.markdownguide.org/basic-syntax/#images-1

> The gpodder logo has a blank alt tag and should be `alt="gPodder logo"`.

That's on purpose, since it's for decoration and doesn't add any "information". See this article:

https://www.w3.org/WAI/tutorials/images/decorative/

The same could actually be argued for the screenshot, so we could remove the alt text there completely.

**Comment by auouymous** [comment]
Sorry for the delay. I don't see any mention of logos and screenshots qualifying as useless decoration. Both are images one might want to link to from another site, and not knowing the image is the project logo or a screenshot would make that difficult.

**Comment by thp** [comment]
> Sorry for the delay. I don't see any mention of logos and screenshots qualifying as useless decoration. Both are images one might want to link to from another site, and not knowing the image is the project logo or a screenshot would make that difficult.

About the screenshot: Yes, it makes sense for it to have an alt tag.

However, as far as conveying information on the webpage for text-only and visually impaired clients the gPodder logo is really just that -- a decoration :) Open the page in Lynx or Links to check out how it looks in text-only mode. The alt tag is displayed as alternative text there instead of the image (and most likely read by screen readers). `alt=""` here means "if the image cannot be displayed, don't show (or read) anything instead of it".

As an example, the Github logo on this page has `aria-hidden="true"` set so that accessibility technology doesn't show it, `alt=""` accomplishes the same thing for `` (as far as i'm aware, anyway :).

**Comment by Keeper-of-the-Keys** [comment]
Op vr 25 mrt. 2022 om 15:27 schreef Thomas Perl ***@***.***>:

> Why is ubuntu ppa with others and not linux?
>
> I figured that since Ubuntu basically wants everybody to use Snaps, the
> Ubuntu PPA is probably only for "experts" (who want to avoid Snap and
> Flatpak), and the beginners should use the Flatpak, so this is placed more
> prominently.
>
gPodder is actually still shipping as a deb on Ubuntu (even in Jammy and I
hope it stays that way).
That being said, the official PPA should be easy to find for people who
want newer versions (when applicable).

**Comment by auouymous** [comment]
Ok, LGTM.

@Keeper-of-the-Keys Are you suggesting the PPA link should be in the linux section instead of other?

**Comment by thp** [comment]
Bump. Should we merge this? :)

**Comment by Keeper-of-the-Keys** [comment]
@auouymous I'm not sure mentioning the PPA is needed, or it should be done with a suggestion to check the "native" repo first (which I guess the "distributions" link is?)

**Comment by auouymous** [comment]
Thanks, the new page looks good.

**Pull request merged**
