### PR TITLE
Add google analytics tracking code

### PR DESCRIPTION
**Pull request by adamvoss**
@thp Is there an existing Tracking ID that should be used?  If not I can create one and grant you all privileges.

### CODE REVIEW

**Comment by elelay** [comment]
Can google analytics be included in the 404 page only?

**Comment by adamvoss** [comment]
@elelay That is be possible.  We would miss out on page view information for the rest of the site though.

**Comment by thp** [comment]
No, I don't have an existing ID. Feel free to create one. My Google account is th.perl (at gmail).

**Comment by elelay** [comment]
@adamvoss I fail to see the point in adding google analytics. Can you elaborate?

**Comment by adamvoss** [comment]
@elelay My primary motivation is to enable the project to be able to answer questions about its website.  Does it have any users?  How many?  Which pages are most popular?  Etc.

The site was self-hosted they could have gotten that information from the web server (if it was so configured), now that it is hosted on the GH Pages platform a JavaScript-based solution is simplest (alternative would be tracking images, but we would need a server to host that).

**Pull request merged**
